import checkJs from "./modules/checkJs";
import date from "./modules/date";
import menuScroll from "./modules/menuScroll";
import modal from "./modules/modal";
import range from "./modules/range";
import scroll from "./modules/scroll";
import slider from "./modules/slider";
import sliderReviews from "./modules/sliderReviews";
import mask from "./modules/mask";
import menu from "./modules/menu";
import calculateForm from "./modules/calculateForm";
import heroForm from "./modules/heroForm";
import modalForm from "./modules/modalForm";
import video from "./modules/video";

checkJs();
slider();
sliderReviews();
scroll();
menuScroll();
range();
date();
modal();
mask();
menu();
calculateForm();
heroForm();
modalForm();
video();
